name: Sharpcomet CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: sharp-comet

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - name: build
        run: dotnet build -c Release

      - name: test
        run: dotnet test -c Release --no-build
      
      - name: publish
        run: dotnet publish -o output comet/comet.csproj

      - name: compile test scripts
        working-directory: ./sharp-comet/output
        run: |
          ls ../../test_scripts/* | xargs -n 1 ./comet -c 
